# Generated by Django 4.2 on 2023-05-03 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("businessapp", "0004_rename_created_location_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="newss",
                to="businessapp.location",
            ),
        ),
        migrations.AlterField(
            model_name="weather",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weathers",
                to="businessapp.location",
            ),
        ),
    ]
