# Generated by Django 4.2 on 2023-05-03 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("businessapp", "0005_alter_news_location_alter_weather_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="news",
                to="businessapp.location",
            ),
        ),
    ]
