# Generated by Django 4.2 on 2023-05-11 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("businessapp", "0006_alter_news_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsWeather",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("news_data", models.TextField()),
                ("weather_data", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="newsweathers",
                        to="businessapp.location",
                    ),
                ),
            ],
        ),
    ]
